package org.immregistries.iis.kernal.logic.recommendations;

import ca.uhn.fhir.jpa.searchparam.SearchParameterMap;
import ca.uhn.fhir.rest.api.MethodOutcome;
import ca.uhn.fhir.rest.client.api.IGenericClient;
import ca.uhn.fhir.rest.param.ReferenceParam;
import org.hl7.fhir.instance.model.api.IAnyResource;
import org.hl7.fhir.instance.model.api.IBaseBundle;
import org.hl7.fhir.r4.model.*;
import org.immregistries.iis.kernal.fhir.common.annotations.OnR4Condition;
import org.immregistries.iis.kernal.logic.CodeMapManagerService;
import org.immregistries.iis.kernal.logic.v2.handling.IncomingQueryHandler;
import org.immregistries.iis.kernal.mapping.mappers.fields.r4.BusinessIdentifierMapperR4;
import org.immregistries.iis.kernal.mapping.mappers.resources.r4.ImmunizationEvaluationMapperR4;
import org.immregistries.iis.kernal.mapping.mappers.resources.r4.ImmunizationRecommendationMapperR4;
import org.immregistries.iis.kernal.mapping.requesters.FhirSearchRequester;
import org.immregistries.iis.kernal.model.*;
import org.immregistries.iis.kernal.persisted.model.Tenant;
import org.immregistries.vfa.connect.model.ForecastActual;
import org.jetbrains.annotations.Nullable;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Conditional;
import org.springframework.stereotype.Service;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import static org.immregistries.iis.kernal.fhir.immds.IRecommendationForecastProvider.EVALUATION;
import static org.immregistries.iis.kernal.fhir.immds.IRecommendationForecastProvider.RECOMMENDATION;

@Service
@Conditional(OnR4Condition.class)
public class ImmunizationRecommendationServiceR4
		implements IImmunizationRecommendationService<ImmunizationRecommendation, Patient> {

	@Autowired
	private IncomingQueryHandler incomingQueryHandler;
	@Autowired
	private FhirSearchRequester fhirSearchRequester;
	@Autowired
	private ImmunizationRecommendationMapperR4 immunizationRecommendationMapperR4;
	@Autowired
	private ImmunizationEvaluationMapperR4 immunizationEvaluationMapperR4;
	@Autowired
	private CodeMapManagerService codeMapManagerService;
	@Autowired
	private BusinessIdentifierMapperR4 businessIdentifierMapper;
	@Autowired
	private IisRecommendationGenerator recommendationGenerator;

	@Override
	public ImmunizationRecommendation generate(Tenant tenant, Date date) {
		return immunizationRecommendationMapperR4.fhirObject(recommendationGenerator.generateRecommendation(tenant, date));
	}

	@Override
	public ImmunizationRecommendation generate(Tenant tenant, Date date, IisPatient iisPatient) {
		return immunizationRecommendationMapperR4.fhirObject(recommendationGenerator.generateRecommendation(tenant, date, iisPatient));
	}

	@Override
	public ImmunizationRecommendation addRandomGeneratedRecommendation(IGenericClient fhirClient, IAnyResource patient) {
		return addRandomGeneratedRecommendation(getPatientRecommendation(fhirClient, patient));
	}

	@Override
	public ImmunizationRecommendation addRandomGeneratedRecommendation(ImmunizationRecommendation recommendation) {
		ForecastActual forecastActual = recommendationGenerator.randomForecast();
		recommendation.addRecommendation(immunizationRecommendationMapperR4.recommendationComponent(forecastActual));
		return recommendation;
//		ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent recommendationComponent = new ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent()
//				.setDescription("Random Sample generated by IIS Sandbox")
//				.setForecastStatus(new CodeableConcept()
//						.addCoding(RecommendationStatus.DUE.toR4()));
//
//		Collection<Code> col = codeMapManagerService.getCodeMap().getCodesForTable(CodesetType.VACCINATION_CVX_CODE);
//		Code cvx = col.stream().skip((int) (col.size() * Math.random())).findFirst().orElseThrow();
//		recommendationComponent.addVaccineCode().addCoding().setSystem(CVX_SYSTEM).setCode(cvx.getValue())
//				.setDisplay(cvx.getLabel());
//
//		int randN = (int) (Math.random() * VaccinationRecommendationDateCode.values().length);
//		int randDateN = (int) (1 + Math.random() * 15);
//		Calendar calendar = Calendar.getInstance();
//		calendar.setTime(new Date());
//		calendar.add(Calendar.DATE, randDateN);
//		calendar.getTime();
//		recommendationComponent.addDateCriterion()
//				.setValue(calendar.getTime())
//				.setCode(new CodeableConcept().addCoding(VaccinationRecommendationDateCode.values()[randN].toR4()));
//
//		recommendation
//			.addRecommendation(recommendationComponent);
//		return recommendation;
	}

	public ImmunizationRecommendation queryCds(Tenant tenant, Date date, IisPatient patientMaster) {
		List<VaccinationMaster> vaccinationMasterList = fhirSearchRequester.searchVaccinationMasterGoldenList(
				new SearchParameterMap("patient",
						new ReferenceParam("Patient/" + patientMaster.getPatientId()).setMdmExpand(true)));
		return (ImmunizationRecommendation) queryCds(tenant, date, patientMaster, vaccinationMasterList)
				.getParameter(RECOMMENDATION).getResource();
	}

	public Parameters queryCds(Tenant tenant, Date date, IisPatient iisPatient,
										List<? extends IisVaccination> vaccinationMasterList) {
		List<ForecastActual> forecastActualList = incomingQueryHandler.doForecast(iisPatient,
				vaccinationMasterList, tenant, date);
		IisRecommendation iisRecommendation = new IisRecommendation(iisPatient, forecastActualList, date);

		ImmunizationRecommendation immunizationRecommendation = immunizationRecommendationMapperR4.fhirObject(iisRecommendation);

		immunizationRecommendation.addIdentifier(new Identifier().setValue(UUID.randomUUID().toString().split("-")[0]));
		immunizationRecommendation.setAuthority(new Reference()
				.setIdentifier(new Identifier().setSystem("IIS-Sandbox/tenantAndLonestar")
						.setValue(tenant.getOrganizationName())));

		Parameters parameters = new Parameters();
		parameters.addParameter().setResource(immunizationRecommendation).setName(RECOMMENDATION);
		for (IisVaccination iisVaccination : vaccinationMasterList) {
			IisEvaluation iisEvaluation = new IisEvaluation(iisVaccination, date);
			ImmunizationEvaluation immunizationEvaluation = immunizationEvaluationMapperR4.fhirObject(iisEvaluation);
			if (immunizationEvaluation != null) {
				parameters.addParameter().setResource(immunizationEvaluation).setName(EVALUATION);
			}
		}
		return parameters;
	}

	public MethodOutcome updateRecommendation(IGenericClient fhirClient, IAnyResource recommendation) {
		return fhirClient.update().resource(recommendation).withId(recommendation.getId()).execute();
	}

	public ImmunizationRecommendation readRecommendation(String recommendationId, String recommendationIdentifier, IGenericClient fhirClient) {
		ImmunizationRecommendation recommendation = null;
		if (recommendationId != null) {
			recommendation = fhirClient.read().resource(ImmunizationRecommendation.class)
				.withId(recommendationId).execute();
		} else if (recommendationIdentifier != null) {
			Bundle recommendationBundle = fhirClient.search()
				.forResource(ImmunizationRecommendation.class).where(
					Patient.IDENTIFIER.exactly().identifier(recommendationIdentifier))
				.returnBundle(Bundle.class).execute();
			if (recommendationBundle.hasEntry()) {
				recommendation = (ImmunizationRecommendation) recommendationBundle
					.getEntryFirstRep().getResource();
			}
		}
		return recommendation;
	}

	public @Nullable ImmunizationRecommendation getPatientRecommendation(IGenericClient fhirClient, IAnyResource patient) {
		ImmunizationRecommendation recommendation = null;
		IBaseBundle baseBundle = fhirClient.search().forResource(ImmunizationRecommendation.class)
			.where(ImmunizationRecommendation.PATIENT
				.hasId(new IdType(patient.getId()).getIdPart()))
			.execute();
		Bundle recommendationBundle = (Bundle) baseBundle;
		if (recommendationBundle.hasEntry()) {
			recommendation = (ImmunizationRecommendation) recommendationBundle
				.getEntryFirstRep().getResource();
		}
		return recommendation;
	}

}
