version: '3.3'
services:
    db:
        image: mysql:latest
        environment:
            MYSQL_HOST_PORT: db:3306
        ports:
            - "33061:3306"
        volumes:
            - ./src/database/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
            - ./src/database/upgrade v0.4.sql:/docker-entrypoint-initdb.d/upgrade v0.4.sql
            - ./src/database/upgrade v0.5BETA.sql:/docker-entrypoint-initdb.d/upgrade v0.5BETA.sql
    web:
        depends_on:
            - db
        build: .
        ports:
            - "8081:8080"
