version: "3"
services:
  hapi-fhir-postgresql:
    image: postgres:13-alpine
    container_name: hapi-fhir-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "hapi_fhir_iis"
      POSTGRES_USER: "hapi_iis_web"
      POSTGRES_PASSWORD: "SicMundusCreatusEst"
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 8s
      timeout: 10s
      retries: 10
      start_period: 5s
#    volumes:
#      - ./database/create-postgresql-for-hapi-fhir.sql:/docker-entrypoint-initdb.d/3.sql
#        - hapi-fhir-postgres:/var/lib/postgresql/data
  iis-sandbox-mysql:
    image: mysql:latest
    container_name: iis-sandbox-mysql
    command:
      --lower_case_table_names=1
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3306/iis_alongside_jpa" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    environment:
      MYSQL_USER: 'iis_web'
      MYSQL_PASSWORD: 'SharkBaitHooHaHa'
      MYSQL_ROOT_PASSWORD: 'password123456789'
    volumes:
      - ./database/create-mysql-database.sql:/docker-entrypoint-initdb.d/1.sql
  iis-sandbox:
#    build: .
    image: clemhen/iis-sandbox:deployable-v1.1
    container_name: iis-sandbox
    #    environment:
    #      - iis.mysql.hibernate.connection.url=jdbc:mysql://iis-sandbox-mysql:3306/iis_alongside_jpa
    #      - IIS_MYSQL_URL=jdbc:mysql://iis-sandbox-mysql:3306/iis_alongside_jpa
    #      - SPRING_DATASOURCE_URL=jdbc:postgresql://hapi-fhir-postgres:5432/hapi_fhir_iis
    #      - spring.datasource.url=jdbc:postgresql://hapi-fhir-postgres:5432/hapi_fhir_iis
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      hapi-fhir-postgresql:
        condition: service_healthy
      iis-sandbox-mysql:
        condition: service_healthy

volumes:
  hapi-fhir-postgres:
  sandbox-mysql: