services:
  iis-sandbox:
    build: .
    image: clemhen/iis-sandbox:latest
    container_name: iis-sandbox-iggy
    env_file: .env
    environment:
      FHIR_VERSION: R4
      # 1. Activate your target H2 profile explicitly
      SPRING_PROFILES_ACTIVE: "h2"

      # 2. Bind your file storage parameters to the newly permissioned system path
      IIS_MYSQL_URL: "jdbc:h2:file:/var/data-h2/usersTenants"
      SPRING_DATASOURCE_URL: "jdbc:h2:file:/var/data-h2/r4"

      # 3. Explicitly declare the driver parameters so the environment maps perfectly
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.h2.Driver"
    restart: unless-stopped
    ports:
      - "8089:8080"
    volumes:
      - iis_h2_storage:/var/data-h2

volumes:
  iis_h2_storage: