<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.immregistries.iis</groupId>
    <artifactId>iis-sandbox</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <repositories>
        <repository>
            <id>hit-nexus</id>
            <url>https://hit-nexus.nist.gov/repository/releases</url>
        </repository>
    </repositories>

    <!-- one-liner to take you to the cloud with settings form the application.yaml file: -->
    <!-- 'mvn clean package com.google.cloud.tools:jib-maven-plugin:dockerBuild -Dimage=distroless-hapi && docker run -p 8080:8080 -e spring.batch.job.enabled=false distroless-hapi' -->
    <!--
    Note: HAPI projects use the "hapi-fhir" POM as their base to provide easy management.
    You do not need to use this in your own projects, so the "parent" tag and it's
    contents below may be removed
    if you are using this file as a basis for your own project.
    -->
    <parent>
        <groupId>ca.uhn.hapi.fhir</groupId>
        <artifactId>hapi-fhir</artifactId>
<!--        WARNING MUST BE THE SAME VALUE AS PROPERTY hapi-fhir.version -->
        <version>8.0.0</version>
    </parent>

    <properties>
        <revision>0.6.3-SNAPSHOT-HAPI-UPGRADE-TEST</revision>
<!--        WARNING MUST BE THE SAME VALUE AS parent hapi-fhir version -->
        <hapi-fhir.version>8.0.0</hapi-fhir.version>
        <java.version>17</java.version>
        <logback-classic.version>1.2.11</logback-classic.version>
    </properties>

    <prerequisites>
        <maven>3.8.3</maven>
    </prerequisites>

    <name>IIS Sandbox</name>

    <modules>
        <module>iis-logic</module>
        <module>iis-web</module>
        <module>iis-core-model</module>
        <module>iis-fhir-annotations</module>
        <module>iis-mapping</module>
        <module>iis-constants</module>
        <module>iis-core-commons</module>
        <module>iis-fhir-bulk-export</module>
        <module>iis-fhir-server</module>
        <module>iis-fhir-logic</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.immregistries.iis</groupId>
                <artifactId>iis-core-model</artifactId>
                <version>${revision}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>flatten-maven-plugin</artifactId>
                <version>1.6.0</version>
                <configuration>
                    <updatePomFile>true</updatePomFile>
                    <flattenMode>resolveCiFriendliesOnly</flattenMode>
                </configuration>
                <executions>
                    <execution>
                        <id>flatten</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>flatten</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>flatten.clean</id>
                        <phase>clean</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
