import {Component, inject, OnInit, signal, ViewChild} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {Button} from 'primeng/button';
import {Table, TableModule} from 'primeng/table';
import {Tag} from 'primeng/tag';
import {Dialog} from 'primeng/dialog';
import {InputText} from 'primeng/inputtext';
import {Textarea} from 'primeng/textarea';
import {Select} from 'primeng/select';
import {IconField} from 'primeng/iconfield';
import {InputIcon} from 'primeng/inputicon';
import {Message} from 'primeng/message';
import {ConfirmDialog} from 'primeng/confirmdialog';
import {ConfirmationService} from 'primeng/api';
import {SubscriptionApiService} from '../../services/subscription-api.service';
import {SubscriptionItem, TriggerRequest} from '../../models/subscription.model';
import {LoadingSpinnerComponent} from '../../../../shared/components/loading-spinner/loading-spinner.component';

const OPERATION_SAMPLE = `{
  "resourceType": "OperationOutcome",
  "id": "generated",
  "issue": [
    {
      "severity": "information",
      "code": "informational",
      "details": { "text": "Autogenerated Sample" }
    }
  ]
}`;

@Component({
  selector: 'app-subscription-page',
  standalone: true,
  imports: [
    FormsModule, Button, TableModule, Tag, Dialog, InputText, Textarea, Select,
    IconField, InputIcon, Message, ConfirmDialog, LoadingSpinnerComponent,
  ],
  providers: [ConfirmationService],
  template: `
    <div class="subscription-page">
      <div class="page-header">
        <h1>Subscriptions</h1>
        @if (!notAvailable()) {
          <p-button label="Create Subscription" icon="pi pi-plus" (onClick)="openCreateDialog()" />
        }
      </div>

      @if (notAvailable()) {
        <p-message severity="warn" styleClass="w-full">
          <ng-template #messageicon>
            <i class="pi pi-exclamation-triangle"></i>
          </ng-template>
          FHIR Subscriptions are only available when the server is running in FHIR R5 mode. The current deployment uses FHIR R4.
        </p-message>
      } @else if (loading()) {
        <app-loading-spinner />
      } @else {
        <p-iconfield class="filter-field">
          <p-inputicon styleClass="pi pi-search" />
          <input pInputText type="text" [(ngModel)]="filterValue" (input)="onFilter()" placeholder="Filter subscriptions..." />
        </p-iconfield>
        <p-table
          #dt
          [value]="subscriptions()"
          [paginator]="true"
          [rows]="10"
          [rowHover]="true"
          [globalFilterFields]="['name', 'endpoint', 'status', 'topic']"
          styleClass="p-datatable-sm"
        >
          <ng-template #header>
            <tr>
              <th pSortableColumn="name">Name <p-sortIcon field="name" /></th>
              <th pSortableColumn="endpoint">Endpoint <p-sortIcon field="endpoint" /></th>
              <th pSortableColumn="status">Status <p-sortIcon field="status" /></th>
              <th>Topic</th>
              <th style="width: 120px"></th>
            </tr>
          </ng-template>
          <ng-template #body let-sub>
            <tr>
              <td>{{ sub.name }}</td>
              <td class="endpoint-cell">{{ sub.endpoint }}</td>
              <td><p-tag [value]="sub.status" [severity]="statusSeverity(sub.status)" /></td>
              <td class="endpoint-cell">{{ sub.topic }}</td>
              <td>
                <p-button icon="pi pi-play" [rounded]="true" [text]="true" size="small" pTooltip="Trigger" (onClick)="openTriggerDialog(sub)" />
                <p-button icon="pi pi-trash" [rounded]="true" [text]="true" size="small" severity="danger" pTooltip="Delete" (onClick)="confirmDelete(sub)" />
              </td>
            </tr>
          </ng-template>
          <ng-template #emptymessage>
            <tr><td colspan="5" class="text-muted" style="text-align: center;">No subscriptions found.</td></tr>
          </ng-template>
        </p-table>
      }

      <!-- Trigger Dialog -->
      <p-dialog header="Trigger Subscription" [(visible)]="triggerDialogVisible" [modal]="true" [style]="{ width: '700px' }">
        @if (selectedSubscription()) {
          <div class="detail-grid">
            <div class="detail-item"><span class="label">Name</span><span>{{ selectedSubscription()!.name }}</span></div>
            <div class="detail-item"><span class="label">Identifier</span><span>{{ selectedSubscription()!.identifier }}</span></div>
            <div class="detail-item"><span class="label">Endpoint</span><span class="endpoint-cell">{{ selectedSubscription()!.endpoint }}</span></div>
            <div class="detail-item"><span class="label">Status</span><p-tag [value]="selectedSubscription()!.status" [severity]="statusSeverity(selectedSubscription()!.status)" /></div>
            <div class="detail-item"><span class="label">Topic</span><span class="endpoint-cell">{{ selectedSubscription()!.topic }}</span></div>
            <div class="detail-item"><span class="label">Content Type</span><span>{{ selectedSubscription()!.contentType || '-' }}</span></div>
          </div>

          <div class="trigger-form">
            <div class="verb-select">
              <label>HTTP Verb</label>
              <p-select [options]="httpVerbs" [(ngModel)]="triggerVerb" />
            </div>
            <label>Message Body</label>
            <textarea pTextarea [(ngModel)]="triggerMessage" [rows]="10" class="message-input"></textarea>
            <div class="trigger-actions">
              <p-button label="Send" icon="pi pi-send" (onClick)="onTrigger()" [loading]="triggering()" />
            </div>
          </div>

          @if (triggerResult()) {
            <p-message severity="success" styleClass="mt-3 w-full">
              <pre class="trigger-result">{{ triggerResult() }}</pre>
            </p-message>
          }
          @if (triggerError()) {
            <p-message severity="error" [text]="triggerError()!" styleClass="mt-3 w-full" />
          }
        }
      </p-dialog>

      <!-- Create Dialog -->
      <p-dialog header="Create Subscription" [(visible)]="createDialogVisible" [modal]="true" [style]="{ width: '500px' }">
        <div class="create-form">
          <div class="form-field">
            <label>Name</label>
            <input pInputText [(ngModel)]="createName" />
          </div>
          <div class="form-field">
            <label>Endpoint URL</label>
            <input pInputText [(ngModel)]="createEndpoint" placeholder="https://..." />
          </div>
          <div class="form-field">
            <label>Topic URL</label>
            <input pInputText [(ngModel)]="createTopic" />
          </div>
          <div class="form-field">
            <label>Content Type</label>
            <input pInputText [(ngModel)]="createContentType" value="application/fhir+json" />
          </div>
        </div>
        <ng-template #footer>
          <p-button label="Create" icon="pi pi-check" (onClick)="onCreate()" [loading]="creating()" />
        </ng-template>
      </p-dialog>

      <p-confirmDialog />
    </div>
  `,
  styles: `
    .subscription-page { max-width: 1100px; }
    .page-header {
      display: flex;
      align-items: center;
      justify-content: space-between;
      margin-bottom: 1rem;
      h1 { margin: 0; }
    }
    .filter-field { margin-bottom: 1rem; }
    .endpoint-cell {
      word-break: break-all;
      font-size: 0.85rem;
    }
    .detail-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 0.75rem;
      margin-bottom: 1.5rem;
    }
    .detail-item {
      display: flex;
      flex-direction: column;
      gap: 0.25rem;
      .label {
        font-size: 0.75rem;
        color: var(--p-text-muted-color);
        text-transform: uppercase;
        letter-spacing: 0.05em;
      }
    }
    .trigger-form {
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
      label {
        font-size: 0.875rem;
        font-weight: 500;
      }
    }
    .verb-select {
      display: flex;
      flex-direction: column;
      gap: 0.375rem;
      max-width: 200px;
    }
    .message-input {
      width: 100%;
      font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
      font-size: 0.8rem;
    }
    .trigger-actions {
      display: flex;
      justify-content: flex-end;
    }
    .trigger-result {
      font-family: 'Cascadia Code', 'Fira Code', 'Consolas', monospace;
      font-size: 0.75rem;
      white-space: pre-wrap;
      word-break: break-word;
      margin: 0;
      max-height: 200px;
      overflow-y: auto;
    }
    .create-form {
      display: flex;
      flex-direction: column;
      gap: 1rem;
    }
    .form-field {
      display: flex;
      flex-direction: column;
      gap: 0.375rem;
      label {
        font-size: 0.875rem;
        font-weight: 500;
      }
      input { width: 100%; }
    }
    .mt-3 { margin-top: 0.75rem; }
    .w-full { width: 100%; }
  `,
})
export class SubscriptionPageComponent implements OnInit {
  private subscriptionApi = inject(SubscriptionApiService);
  private confirmationService = inject(ConfirmationService);

  @ViewChild('dt') table!: Table;

  subscriptions = signal<SubscriptionItem[]>([]);
  loading = signal(false);
  notAvailable = signal(false);
  filterValue = '';

  selectedSubscription = signal<SubscriptionItem | null>(null);
  triggerDialogVisible = signal(false);
  triggerMessage = OPERATION_SAMPLE;
  triggerVerb = 'PUT';
  triggering = signal(false);
  triggerResult = signal<string | null>(null);
  triggerError = signal<string | null>(null);
  httpVerbs = ['PUT', 'POST', 'DELETE'];

  createDialogVisible = signal(false);
  createName = '';
  createEndpoint = '';
  createTopic = '';
  createContentType = 'application/fhir+json';
  creating = signal(false);

  ngOnInit(): void {
    this.loadSubscriptions();
  }

  onFilter(): void {
    this.table.filterGlobal(this.filterValue, 'contains');
  }

  openTriggerDialog(sub: SubscriptionItem): void {
    this.selectedSubscription.set(sub);
    this.triggerMessage = OPERATION_SAMPLE;
    this.triggerVerb = 'PUT';
    this.triggerResult.set(null);
    this.triggerError.set(null);
    this.triggerDialogVisible.set(true);
  }

  onTrigger(): void {
    const sub = this.selectedSubscription();
    if (!sub) return;

    this.triggering.set(true);
    this.triggerResult.set(null);
    this.triggerError.set(null);

    const request: TriggerRequest = {
      subscriptionId: sub.identifier,
      messages: [this.triggerMessage],
      httpVerbs: [this.triggerVerb],
    };

    this.subscriptionApi.trigger(request).subscribe({
      next: (result) => {
        this.triggerResult.set(result);
        this.triggering.set(false);
      },
      error: (err) => {
        this.triggerError.set(err.message || 'Trigger failed');
        this.triggering.set(false);
      },
    });
  }

  openCreateDialog(): void {
    this.createName = '';
    this.createEndpoint = '';
    this.createTopic = '';
    this.createContentType = 'application/fhir+json';
    this.createDialogVisible.set(true);
  }

  onCreate(): void {
    this.creating.set(true);
    const subscription = {
      resourceType: 'Subscription',
      status: 'requested',
      name: this.createName,
      endpoint: this.createEndpoint,
      topic: this.createTopic,
      contentType: this.createContentType,
      channelType: {system: 'http://terminology.hl7.org/CodeSystem/subscription-channel-type', code: 'rest-hook'},
    };
    this.subscriptionApi.create(subscription).subscribe({
      next: () => {
        this.creating.set(false);
        this.createDialogVisible.set(false);
        this.loadSubscriptions();
      },
      error: () => this.creating.set(false),
    });
  }

  confirmDelete(sub: SubscriptionItem): void {
    this.confirmationService.confirm({
      message: `Delete subscription "${sub.name}"?`,
      header: 'Confirm Delete',
      icon: 'pi pi-exclamation-triangle',
      acceptButtonStyleClass: 'p-button-danger',
      accept: () => {
        this.subscriptionApi.delete(sub.id).subscribe({
          next: () => this.loadSubscriptions(),
        });
      },
    });
  }

  statusSeverity(status: string): 'success' | 'info' | 'warn' | 'danger' | 'secondary' {
    switch (status?.toLowerCase()) {
      case 'active':
        return 'success';
      case 'requested':
        return 'info';
      case 'error':
        return 'danger';
      case 'off':
        return 'secondary';
      default:
        return 'warn';
    }
  }

  private loadSubscriptions(): void {
    this.loading.set(true);
    this.subscriptionApi.getAll().subscribe({
      next: (items) => {
        this.subscriptions.set(items);
        this.loading.set(false);
      },
      error: (err) => {
        if (err.status === 404) {
          this.notAvailable.set(true);
        }
        this.loading.set(false);
      },
    });
  }
}
