<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.immregistries.iis</groupId>
        <artifactId>iis-sandbox</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>iis-logic</artifactId>
    <packaging>jar</packaging>
    <name>IIS Sandbox Logic</name>

    <repositories>
        <repository>
            <id>hit-nexus</id>
            <url>https://hit-nexus.nist.gov/repository/releases</url>
        </repository>
    </repositories>

    <properties>
        <java.version>17</java.version>
        <logback-classic.version>1.2.11</logback-classic.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-constants</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-core-model</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-core-commons</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-mapping</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-fhir-annotations</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-fhir-bulk-export</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-fhir-logic</artifactId>
            <version>${revision}</version>
        </dependency>


        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.18.0</version>
        </dependency>

        <dependency>
            <groupId>jakarta.interceptor</groupId>
            <artifactId>jakarta.interceptor-api</artifactId>
            <scope>provided</scope>
        </dependency>


    </dependencies>


</project>
