worldName: Alma
islandName: Alpha
generation: 1
generationScore: 0.0
generatedDate: "2024-04-03 12:00:00"
scoringWeights:
  shouldMatch_Matches: 12
  shouldMatch_Possible: 10
  shouldMatch_NoMatch: -10
  shouldPossible_Matches: 8
  shouldPossible_Possible: 10
  shouldPossible_NoMatch: -8
  shouldNoMatch_Matches: -10
  shouldNoMatch_Possible: -8
  shouldNoMatch_NoMatch: 10
Match:
  label: Match
  enabled: true
  minScore: 0.0
  maxScore: 1.0
  Household:
    label: Household
    enabled: true
    minScore: 0.0
    maxScore: 0.4
    Last Name:
      label: Last Name
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      L-match:
        label: L-match
        detector: ExactMatchNode
        fieldName: nameLast
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      L-similar:
        label: L-similar
        detector: SimilarMatchNode
        fieldName: nameLast
        enabled: true
        minScore: 0.0
        maxScore: 0.4
      L-hyphenated:
        label: L-hyphenated
        detector: HyphenMatchNode
        fieldName: nameLast
        enabled: true
        minScore: 0.0
        maxScore: 0.6
    Guardian:
      label: Guardian
      enabled: false
      minScore: 0.0
      maxScore: 0.3
      GF-match:
        label: GF-match
        detector: ExactMatchNode
        fieldName: guardianNameFirst
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      GL-match:
        label: GL-match
        detector: ExactMatchNode
        fieldName: guardianNameLast
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      GF-GL-match:
        label: GF-GL-match
        detector: ExactMatchNode
        fieldName: guardianNameFirst
        fieldNameOther: guardianNameLast
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      MM-match:
        label: MM-match
        detector: ExactMatchNode
        fieldName: motherMaidenName
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      GL-MM-match:
        label: GL-MM-match
        detector: ExactMatchNode
        fieldName: motherMaidenName
        fieldNameOther: guardianNameLast
        enabled: false
        minScore: 0.0
        maxScore: 0.5
    Location:
      label: Location
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      PN-match:
        label: PN-match
        detector: ExactMatchNode
        fieldName: phone
        enabled: true
        minScore: 0.0
        maxScore: 0.5
      AD-match:
        label: AD-match
        detector: AddressMatchNode
        enabled: true
        minScore: 0.0
        maxScore: 0.7
  Person:
    label: Person
    enabled: true
    minScore: 0.0
    maxScore: 0.6
    Patient Id:
      label: Patient Id
      enabled: false
      minScore: 0.0
      maxScore: 0.8
      MRN-match:
        label: MRN-match
        detector: AtLeastOneExactMatchNode
        fieldName: mrns
        splitParameter: "|"
        enabled: false
        minScore: 0.0
        maxScore: 0.9
      SSN-match:
        label: SSN-match
        detector: ExactMatchNode
        fieldName: ssn
        enabled: false
        minScore: 0.0
        maxScore: 0.7
      MA-match:
        label: MA-match
        detector: ExactMatchNode
        fieldName: medicaid
        enabled: false
        minScore: 0.0
        maxScore: 0.9
    First Name:
      label: First Name
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      F-match:
        label: F-match
        detector: ExactMatchNode
        fieldName: nameFirst
        enabled: true
        minScore: 0.0
        maxScore: 0.9
      F-similar:
        label: F-similar
        detector: SimilarMatchNode
        fieldName: nameFirst
        enabled: true
        minScore: 0.0
        maxScore: 0.5
      F-middle:
        label: F-middle
        detector: ExactMatchNode
        fieldName: nameFirst
        fieldNameOther: nameMiddle
        enabled: true
        minScore: 0.0
        maxScore: 0.4
      A-match:
        label: A-match
        detector: ExactMatchNode
        fieldName: nameFirst
        fieldNameOther: nameAlias
        enabled: false
        minScore: 0.0
        maxScore: 0.4
      G-match:
        label: G-match
        detector: ExactMatchNode
        fieldName: gender
        enabled: false
        minScore: 0.0
        maxScore: 0.1
    Birth Order:
      label: Birth Order
      enabled: false
      minScore: 0.0
      maxScore: 0.1
      BO-matches:
        label: BO-matches
        detector: BirthOrderMatchNode
        enabled: false
        minScore: 0.0
        maxScore: 1.0
      MBS-no:
        label: MBS-no
        detector: BirthNotIndicatedMatchNode
        enabled: false
        minScore: 0.0
        maxScore: 0.5
    DOB:
      label: DOB
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      DOB-match:
        label: DOB-match
        detector: ExactMatchNode
        fieldName: birthDate
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      DOB-similar:
        label: DOB-similar
        detector: SimilarDateMatchNode
        fieldName: birthDate
        enabled: true
        minScore: 0.0
        maxScore: 0.65
    Middle Name:
      label: Middle Name
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      M-match:
        label: M-match
        detector: ExactMatchNode
        fieldName: nameMiddle
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      M-initial:
        label: M-initial
        detector: SameInitialMatchNode
        fieldName: nameMiddle
        enabled: true
        minScore: 0.0
        maxScore: 0.6
      M-similar:
        label: M-similar
        detector: SimilarMatchNode
        fieldName: nameMiddle
        enabled: true
        minScore: 0.0
        maxScore: 0.6
      S-match:
        label: S-match
        detector: DoNotConflictMatchNode
        fieldName: nameSuffix
        enabled: false
        minScore: 0.0
        maxScore: 0.1
    Shot History:
      label: Shot History
      enabled: false
      minScore: 0.0
      maxScore: 0.2
      SH-match:
        label: SH-match
        detector: HistoryMatchNode
        fieldName: shotHistory
        enabled: false
        minScore: 0.0
        maxScore: 0.1
Not Match:
  label: Not Match
  enabled: true
  minScore: 0.0
  maxScore: 1.0
  Household:
    label: Household
    enabled: true
    minScore: 0.0
    maxScore: 0.4
    Last Name:
      label: Last Name
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      L-not-match:
        label: L-not-match
        detector: ExactMatchNode
        fieldName: nameLast
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      L-not-similar:
        label: L-not-similar
        detector: SimilarMatchNode
        fieldName: nameLast
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.4
      L-not-hyphenated:
        label: L-not-hyphenated
        detector: HyphenMatchNode
        fieldName: nameLast
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.6
    Guardian:
      label: Guardian
      enabled: false
      minScore: 0.0
      maxScore: 0.3
      GF-not-match:
        label: GF-not-match
        detector: ExactMatchNode
        fieldName: guardianNameFirst
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      GL-not-match:
        label: GL-not-match
        detector: ExactMatchNode
        fieldName: guardianNameLast
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      MM-not-match:
        label: MM-not-match
        detector: ExactMatchNode
        fieldName: motherMaidenName
        not: false
        enabled: true
        minScore: 0.0
        maxScore: 0.5
      MM-not-similar:
        label: MM-not-similar
        detector: SimilarMatchNode
        fieldName: motherMaidenName
        not: false
        enabled: true
        minScore: 0.0
        maxScore: 0.5
    Location:
      label: Location
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      PN-not-match:
        label: PN-not-match
        detector: ExactMatchNode
        fieldName: phone
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.4
      AD-not-match:
        label: AD-not-match
        detector: AddressMatchNode
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.9
  Person:
    label: Person
    enabled: true
    minScore: 0.0
    maxScore: 0.6
    Patient Id:
      label: Patient Id
      enabled: false
      minScore: 0.0
      maxScore: 0.8
      MRN-not-match:
        label: MRN-not-match
        detector: AtLeastOneExactMatchNode
        fieldName: mrns
        splitParameter: "|"
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.05
      SSN-not-match:
        label: SSN-not-match
        detector: ExactMatchNode
        fieldName: ssn
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.9
      MA-not-match:
        label: MA-not-match
        detector: ExactMatchNode
        fieldName: medicaid
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.6
    First Name:
      label: First Name
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      F-not-match:
        label: F-not-match
        detector: ExactMatchNode
        fieldName: nameFirst
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.3
      F-not-similar:
        label: F-not-similar
        detector: SimilarMatchNode
        fieldName: nameFirst
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.3
      F-not-middle:
        label: F-not-middle
        detector: ExactMatchNode
        fieldName: nameMiddle
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.0
      A-not-match:
        label: A-not-match
        detector: ExactMatchNode
        fieldName: nameAlias
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.0
    Gender:
      label: Gender
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      G-not-match:
        label: G-not-match
        detector: ExactMatchNode
        fieldName: gender
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.0
    DOB:
      label: DOB
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      DOB-not-match:
        label: DOB-not-match
        detector: ExactMatchNode
        fieldName: birthDate
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      DOB-not-similar:
        label: DOB-not-similar
        detector: SimilarDateMatchNode
        fieldName: birthDate
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.65
    Middle Name:
      label: Middle Name
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      M-not-match:
        label: M-not-match
        detector: ExactMatchNode
        fieldName: nameMiddle
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      M-not-initial:
        label: M-not-initial
        detector: SameInitialMatchNode
        fieldName: nameMiddle
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.6
      M-not-similar:
        label: M-not-similar
        detector: SimilarMatchNode
        fieldName: nameMiddle
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.6
      S-not-match:
        label: S-not-match
        detector: DoNotConflictMatchNode
        fieldName: nameSuffix
        not: true
        enabled: true
        minScore: 0.0
        maxScore: 0.1
    Shot History:
      label: Shot History
      enabled: false
      minScore: 0.0
      maxScore: 0.2
      SH-not-match:
        label: SH-not-match
        detector: HistoryMatchNode
        fieldName: shotHistory
        not: true
        enabled: false
        minScore: 0.0
        maxScore: 0.1
Twin:
  label: Suspect Twin
  enabled: true
  minScore: 0.0
  maxScore: 1.0
  Name Different:
    label: Name Different
    enabled: true
    minScore: 0.0
    maxScore: 0.2
    F-not-match:
      label: F-not-match
      detector: ExactMatchNode
      fieldName: nameFirst
      not: true
      enabled: true
      minScore: 0.0
      maxScore: 0.5
    F-not-similar:
      label: F-not-similar
      detector: SimilarMatchNode
      fieldName: nameFirst
      not: true
      enabled: true
      minScore: 0.0
      maxScore: 0.6
    M-not-match:
      label: M-not-match
      detector: ExactMatchNode
      fieldName: nameMiddle
      not: true
      enabled: true
      minScore: 0.0
      maxScore: 0.5
    G-not-match:
      label: G-not-match
      detector: ExactMatchNode
      fieldName: gender
      not: true
      enabled: false
      minScore: 0.0
      maxScore: 0.5
  Birth Date:
    label: Birth Date
    enabled: true
    minScore: 0.0
    maxScore: 0.2
    DOB-match:
      label: DOB-match
      detector: ExactMatchNode
      not: true
      enabled: true
      minScore: 0.0
      maxScore: 1.0
  Birth Status:
    label: Birth Status
    enabled: false
    minScore: 0.0
    maxScore: 0.6
    MBS-maybe:
      label: MBS-maybe
      detector: BirthMayBeTwinMatchNode
      enabled: false
      minScore: 0.0
      maxScore: 0.5
    MBS-yes:
      label: MBS-yes
      detector: BirthHasTwinMatchNode
      enabled: false
      minScore: 0.0
      maxScore: 0.1
Missing:
  label: Missing
  enabled: true
  minScore: 0.0
  maxScore: 1.0
  Household:
    label: Household
    enabled: true
    minScore: 0.0
    maxScore: 0.4
    L-missing:
      label: L-missing
      detector: MissingMatchNode
      fieldName: nameLast
      enabled: true
      minScore: 0.0
      maxScore: 0.5
    Household:
      label: Household
      enabled: false
      minScore: 0.0
      maxScore: 0.4
      GFN-missing:
        label: GFN-missing
        detector: MissingMatchNode
        fieldName: guardianNameFirst
        enabled: false
        minScore: 0.0
        maxScore: 0.3
      GLN-missing:
        label: GLN-missing
        detector: MissingMatchNode
        fieldName: guardianNameLast
        enabled: false
        minScore: 0.0
        maxScore: 0.3
      MMN-missing:
        label: MMN-missing
        detector: MissingMatchNode
        fieldName: motherMaidenName
        enabled: false
        minScore: 0.0
        maxScore: 0.3
    Location:
      label: Location
      enabled: true
      minScore: 0.0
      maxScore: 0.4
      PN-missing:
        label: PN-missing
        detector: MissingMatchNode
        fieldName: phone
        enabled: true
        minScore: 0.0
        maxScore: 0.2
      AS1-missing:
        label: AS1-missing
        detector: MissingMatchNode
        fieldName: addressStreet1
        fieldName2: address2Street1
        fieldName3: address3Street1
        enabled: true
        minScore: 0.0
        maxScore: 0.4
      AS2-missing:
        label: AS2-missing
        detector: MissingMatchNode
        fieldName: addressStreet2
        fieldName2: address2Street2
        fieldName3: address3Street2
        enabled: false
        minScore: 0.0
        maxScore: 0.0
      AC-missing:
        label: AC-missing
        detector: MissingMatchNode
        fieldName: addressCity
        fieldName2: address2City
        fieldName3: address3City
        enabled: true
        minScore: 0.0
        maxScore: 0.0
      AS-missing:
        label: AS-missing
        detector: MissingMatchNode
        fieldName: addressState
        fieldName2: address2State
        fieldName3: address3State
        enabled: true
        minScore: 0.0
        maxScore: 0.05
      AZ-missing:
        label: AZ-missing
        detector: MissingMatchNode
        fieldName: addressZip
        fieldName2: address2Zip
        fieldName3: address3Zip
        enabled: true
        minScore: 0.0
        maxScore: 0.0
  Person:
    label: Person
    enabled: true
    minScore: 0.0
    maxScore: 0.6
    Patient Id:
      label: Patient Id
      enabled: false
      minScore: 0.0
      maxScore: 0.3
      MRN-missing:
        label: MRN-missing
        detector: MissingMatchNode
        fieldName: mrns
        enabled: false
        minScore: 0.0
        maxScore: 1.0
      SSN-missing:
        label: SSN-missing
        detector: MissingMatchNode
        fieldName: ssn
        enabled: false
        minScore: 0.0
        maxScore: 0.4
      MA-missing:
        label: MA-missing
        detector: MissingMatchNode
        fieldName: medicaid
        enabled: false
        minScore: 0.0
        maxScore: 0.4
    First Name:
      label: First Name
      enabled: true
      minScore: 0.0
      maxScore: 0.3
      F-missing:
        label: F-missing
        detector: MissingMatchNode
        fieldName: nameFirst
        enabled: true
        minScore: 0.0
        maxScore: 1.0
      A-missing:
        label: A-missing
        detector: MissingMatchNode
        fieldName: nameAlias
        enabled: false
        minScore: 0.0
        maxScore: 0.0
      S-missing:
        label: S-missing
        detector: MissingMatchNode
        fieldName: nameSuffix
        enabled: false
        minScore: 0.0
        maxScore: 0.0
      G-missing:
        label: G-missing
        detector: MissingMatchNode
        fieldName: gender
        enabled: false
        minScore: 0.0
        maxScore: 0.6
    Birth Order:
      label: Birth Order
      enabled: false
      minScore: 0.0
      maxScore: 0.1
      MBS-missing:
        label: MBS-missing
        detector: MissingMatchNode
        fieldName: birthStatus
        enabled: false
        minScore: 0.0
        maxScore: 1.0
      BM-missing:
        label: BM-missing
        detector: MissingMatchNode
        fieldName: birthType
        enabled: false
        minScore: 0.0
        maxScore: 0.5
      BO-missing:
        label: BO-missing
        detector: MissingMatchNode
        fieldName: birthOrder
        enabled: false
        minScore: 0.0
        maxScore: 0.5
    DOB-missing:
      label: DOB-missing
      detector: MissingMatchNode
      fieldName: birthDate
      enabled: true
      minScore: 0.0
      maxScore: 0.4
    M-missing:
      label: M-missing
      detector: MissingMatchNode
      fieldName: nameMiddle
      enabled: true
      minScore: 0.0
      maxScore: 0.2
    SH-missing:
      label: SH-missing
      detector: MissingMatchNode
      fieldName: shotHistory
      enabled: false
      minScore: 0.0
      maxScore: 0.2