package org.immregistries.iis.kernal.logic;

import ca.uhn.fhir.jpa.searchparam.SearchParameterMap;
import ca.uhn.fhir.rest.param.ReferenceParam;
import org.hl7.fhir.r5.model.*;
import org.immregistries.codebase.client.generated.Code;
import org.immregistries.codebase.client.reference.CodesetType;
import org.immregistries.iis.kernal.fhir.common.annotations.OnR5Condition;
import org.immregistries.iis.kernal.logic.messageHandling.IncomingQueryHandler;
import org.immregistries.iis.kernal.mapping.fieldsMappers.BusinessIdentifierMapper;
import org.immregistries.iis.kernal.mapping.internalClient.FhirSearchRequester;
import org.immregistries.iis.kernal.mapping.resourceMappers.forR5.ImmunizationEvaluationMapperR5;
import org.immregistries.iis.kernal.mapping.resourceMappers.forR5.ImmunizationRecommendationMapperR5;
import org.immregistries.iis.kernal.mapping.resourceMappers.forR5.PatientMapperR5;
import org.immregistries.iis.kernal.model.IisPatient;
import org.immregistries.iis.kernal.model.IisVaccination;
import org.immregistries.iis.kernal.model.VaccinationMaster;
import org.immregistries.iis.kernal.persisted.model.Tenant;
import org.immregistries.vfa.connect.model.ForecastActual;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Conditional;
import org.springframework.stereotype.Service;

import java.util.*;

import static org.immregistries.iis.kernal.fhir.immdsForecast.IRecommendationForecastProvider.EVALUATION;
import static org.immregistries.iis.kernal.fhir.immdsForecast.IRecommendationForecastProvider.RECOMMENDATION;
import static org.immregistries.iis.kernal.mapping.resourceMappers.ImmunizationMapper.CVX_SYSTEM;

@Service
@Conditional(OnR5Condition.class)
public class ImmunizationRecommendationServiceR5
		implements IImmunizationRecommendationService<ImmunizationRecommendation, Patient> {

	@Autowired
	private IncomingQueryHandler incomingQueryHandler;
	@Autowired
	FhirSearchRequester fhirSearchRequester;
	@Autowired
	private ImmunizationRecommendationMapperR5 immunizationRecommendationMapperR5;
	@Autowired
	private ImmunizationEvaluationMapperR5 immunizationEvaluationMapperR5;
	@Autowired
	private PatientMapperR5 patientMapperR5;
	@Autowired
	private CodeMapManagerService codeMapManagerService;
	@Autowired
	private BusinessIdentifierMapper businessIdentifierMapper;

	@Override
	public ImmunizationRecommendation generate(Tenant tenant, Date date) {
		ImmunizationRecommendation recommendation = new ImmunizationRecommendation();
		recommendation.addIdentifier(new Identifier().setValue(UUID.randomUUID().toString().split("-")[0]));
		recommendation.setDate(new Date());
		recommendation = addRandomGeneratedRecommendation(recommendation);
		recommendation.setAuthority(new Reference()
				.setIdentifier(
						new Identifier().setSystem("IIS-Sandbox/tenant").setValue(tenant.getOrganizationName()))); // TODO
																													// change
																													// set
																													// system,
																													// register
																													// as
																													// org
		return recommendation;
	}

	@Override
	public ImmunizationRecommendation generate(Tenant tenant, Date date, IisPatient iisPatient) {
		ImmunizationRecommendation recommendation = this.generate(tenant, date);
		recommendation.setPatient(new Reference()
			.setIdentifier(businessIdentifierMapper.toR5(iisPatient.getMainBusinessIdentifier())));
		return recommendation;
	}

	@Override
	public ImmunizationRecommendation addRandomGeneratedRecommendation(ImmunizationRecommendation recommendation) {
		ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent recommendationComponent = recommendation
				.addRecommendation()
				.setDescription("Random Sample generated by IIS Sandbox")
				.setForecastStatus(new CodeableConcept()
						.addCoding(new Coding(IMMUNIZATION_RECOMMENDATION_STATUS_SYSTEM, "due", "Due")));

		Collection<Code> col = codeMapManagerService.getCodeMap().getCodesForTable(CodesetType.VACCINATION_CVX_CODE);
		Code cvx = col.stream().skip((int) (col.size() * Math.random())).findFirst().orElseThrow();
		recommendationComponent.addVaccineCode().addCoding().setSystem(CVX_SYSTEM).setCode(cvx.getValue())
				.setDisplay(cvx.getLabel());

		int randN = (int) (Math.random() * VaccinationRecommendationDateCode.values().length);
		int randDateN = (int) (1 + Math.random() * 15);
		Calendar calendar = Calendar.getInstance();
		calendar.setTime(new Date());
		calendar.add(Calendar.DATE, randDateN);
		calendar.getTime();
		recommendationComponent.addDateCriterion()
				.setValue(calendar.getTime())
				.setCode(new CodeableConcept().addCoding(new Coding(IMMUNIZATION_RECOMMENDATION_DATE_CRITERION_SYSTEM,
						VaccinationRecommendationDateCode.values()[randN].getCode(),
						VaccinationRecommendationDateCode.values()[randN].getLabel())));
		return recommendation;
	}

	public ImmunizationRecommendation queryCds(Tenant tenant, Date date, IisPatient iisPatient) {
		List<VaccinationMaster> vaccinationMasterList = fhirSearchRequester.searchVaccinationMasterGoldenList(
				new SearchParameterMap("patient",
					new ReferenceParam("Patient/" + iisPatient.getPatientId()).setMdmExpand(true)));
		return (ImmunizationRecommendation) queryCds(tenant, date, iisPatient, vaccinationMasterList)
				.getParameter(RECOMMENDATION).getResource();
	}

	public Parameters queryCds(Tenant tenant, Date date, IisPatient iisPatient,
										List<? extends IisVaccination> iisVaccinationList) {
		List<ForecastActual> forecastActualList = incomingQueryHandler.doForecast(iisPatient,
			iisVaccinationList, tenant, date);
		ImmunizationRecommendation immunizationRecommendation = immunizationRecommendationMapperR5
			.toFhir(forecastActualList, date, iisPatient);
		immunizationRecommendation.addIdentifier(new Identifier().setValue(UUID.randomUUID().toString().split("-")[0]));
		immunizationRecommendation.setAuthority(new Reference()
				.setIdentifier(new Identifier().setSystem("IIS-Sandbox/tenantAndLonestar")
						.setValue(tenant.getOrganizationName())));

		Parameters parameters = new Parameters();
		parameters.addParameter().setResource(immunizationRecommendation).setName(RECOMMENDATION);
		for (IisVaccination iisVaccination : iisVaccinationList) {
			ImmunizationEvaluation immunizationEvaluation = immunizationEvaluationMapperR5.toFhir(iisVaccination,
					date);
			if (immunizationEvaluation != null) {
				parameters.addParameter().setResource(immunizationEvaluation).setName(EVALUATION);
			}
		}
		return parameters;
	}

}
