package org.immregistries.iis.kernal.logic.recommendations;

import ca.uhn.fhir.context.FhirContext;
import ca.uhn.fhir.context.FhirVersionEnum;
import org.hl7.fhir.instance.model.api.IAnyResource;
import org.immregistries.codebase.client.generated.Code;
import org.immregistries.codebase.client.reference.CodesetType;
import org.immregistries.iis.kernal.enums.VaccinationRecommendationDateCode;
import org.immregistries.iis.kernal.enums.VaccinePlanStatus;
import org.immregistries.iis.kernal.logic.CodeMapManagerService;
import org.immregistries.iis.kernal.mapping.mappers.resources.RecommendationMapper;
import org.immregistries.iis.kernal.model.BusinessIdentifier;
import org.immregistries.iis.kernal.model.IisPatient;
import org.immregistries.iis.kernal.model.IisRecommendation;
import org.immregistries.iis.kernal.persisted.entities.Tenant;
import org.immregistries.vfa.connect.model.ForecastActual;
import org.immregistries.vfa.connect.model.VaccineGroup;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class IisRecommendationGenerator {
	public static final String AUTHORITY_SYSTEM = "IIS-Sandbox/tenant";
	public static final String DEFAULT_DESCRIPTION = "Random Sample generated by IIS Sandbox";
	@Autowired
	private CodeMapManagerService codeMapManagerService;
	@Autowired
	private RecommendationMapper recommendationMapper;
	@Autowired
	private FhirContext fhirContext;

	public IAnyResource addRandomGeneratedRecommendation(IAnyResource recommendation) {
		ForecastActual forecastActual = randomForecast();
		if (fhirContext.getVersion().getVersion().equals(FhirVersionEnum.R4)) {
			org.hl7.fhir.r4.model.ImmunizationRecommendation immunizationRecommendation = (org.hl7.fhir.r4.model.ImmunizationRecommendation) recommendation;
			org.hl7.fhir.r4.model.ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent component =
				(org.hl7.fhir.r4.model.ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent) recommendationMapper.recommendationComponent(forecastActual);
			immunizationRecommendation.addRecommendation(component);
		} else if (fhirContext.getVersion().getVersion().equals(FhirVersionEnum.R5)) {
			org.hl7.fhir.r5.model.ImmunizationRecommendation immunizationRecommendation = (org.hl7.fhir.r5.model.ImmunizationRecommendation) recommendation;
			org.hl7.fhir.r5.model.ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent component =
				(org.hl7.fhir.r5.model.ImmunizationRecommendation.ImmunizationRecommendationRecommendationComponent) recommendationMapper.recommendationComponent(forecastActual);
			immunizationRecommendation.addRecommendation(component);
		}
		return recommendation;
	}

	/**
	 * Generate a random Immunization Recommendation on specific date
	 *
	 * @param tenant Tenant
	 * @param date   date of recommendation
	 * @return ImmunizationRecommendation resource
	 */
	public IAnyResource generateFhirRecommendation(Tenant tenant, Date date, IisPatient iisPatient) {
		return recommendationMapper.fhirObject(generateRecommendation(tenant, date, iisPatient));
	}


	/**
	 * Generate a random Immunization Recommendation on specific date for patient
	 *
	 * @param tenant          Tenant
	 * @param date            date of recommendation
	 * @param iisPatient patient
	 * @return ImmunizationRecommendation resource
	 */
	public IisRecommendation generateRecommendation(Tenant tenant, Date date, IisPatient iisPatient) {
		IisRecommendation iisRecommendation = generateRecommendation(tenant, date);
		iisRecommendation.setIisPatient(iisPatient);
		return iisRecommendation;
	}

	public IisRecommendation generateRecommendation(Tenant tenant, Date date) {
		IisRecommendation iisRecommendation = new IisRecommendation();
		iisRecommendation.setDescription(DEFAULT_DESCRIPTION);

		iisRecommendation.setVaccinePlanStatus(randomVaccinePlanStatus());
		BusinessIdentifier businessIdentifier = new BusinessIdentifier();
		businessIdentifier.setValue(UUID.randomUUID().toString().split("-")[0]);
		iisRecommendation.setBusinessIdentifierList(List.of(businessIdentifier));

		iisRecommendation.setDate(date);

		BusinessIdentifier authority = new BusinessIdentifier();
		authority.setSystem(AUTHORITY_SYSTEM);
		authority.setValue(tenant.getOrganizationName());
		iisRecommendation.setAuthority(authority);

		ForecastActual forecastActual = randomForecast();
		iisRecommendation.getForecastActualList().add(forecastActual);

		return iisRecommendation;
	}

	public ForecastActual randomForecast() {
		ForecastActual forecastActual = new ForecastActual();
		forecastActual.setExplanationHtml(DEFAULT_DESCRIPTION);
		forecastActual.setScheduleName("");

		Collection<Code> col = codeMapManagerService.getCodeMap().getCodesForTable(CodesetType.VACCINATION_CVX_CODE);
		Code randomCvx = col.stream().skip((int) (col.size() * Math.random())).findFirst().orElseThrow();
		forecastActual.setVaccineCvx(randomCvx.getValue());
		VaccineGroup vaccineGroup = new VaccineGroup();
		vaccineGroup.setVaccineCvx(randomCvx.getValue());
		forecastActual.setVaccineGroup(vaccineGroup);

		Calendar calendar = randomCalendar();

		double random = Math.random();
		if (random < 0.25) {
			forecastActual.setDueDate(calendar.getTime());
		} else if (random < 0.5) {
			forecastActual.setOverdueDate(calendar.getTime());
		} else if (random < 0.75) {
			forecastActual.setFinishedDate(calendar.getTime());
		} else {
			forecastActual.setValidDate(calendar.getTime());
		}
		return forecastActual;

	}

	public VaccinationRecommendationDateCode randomVaccinationRecommendationDateCode() {
		int randN = (int) (Math.random() * VaccinationRecommendationDateCode.values().length);
		VaccinationRecommendationDateCode vaccinationRecommendationDateCode = VaccinationRecommendationDateCode.values()[randN];
		return vaccinationRecommendationDateCode;
	}

	public VaccinePlanStatus randomVaccinePlanStatus() {
		int randN = (int) (Math.random() * VaccinePlanStatus.values().length);
		return VaccinePlanStatus.values()[randN];
	}

	public Calendar randomCalendar() {
		int randDateN = (int) (1 + Math.random() * 15);
		Calendar calendar = Calendar.getInstance();
		calendar.setTime(new Date());
		calendar.add(Calendar.DATE, randDateN);
		calendar.getTime();
		return calendar;
	}
}
