<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.immregistries.iis</groupId>
        <artifactId>iis-sandbox</artifactId>
        <version>${iis.sandbox.revision}</version>
    </parent>

    <artifactId>iis-smart-health-link-card</artifactId>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-core-model</artifactId>
            <version>${iis.sandbox.revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-core-commons</artifactId>
            <version>${iis.sandbox.revision}</version>
        </dependency>
        <dependency>
            <groupId>org.immregistries.iis</groupId>
            <artifactId>iis-constants</artifactId>
            <version>${iis.sandbox.revision}</version>
        </dependency>
    </dependencies>

</project>