<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.immregistries.iis</groupId>
    <artifactId>iis-sandbox</artifactId>
    <version>${revision}</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>iis-client</artifactId>
  <packaging>jar</packaging>
  <name>IIS Sandbox Client</name>

  <properties>
    <node.version>v24.16.0</node.version>
    <npm.version>11.13.0</npm.version>
    <frontend-maven-plugin.version>1.15.1</frontend-maven-plugin.version>
    <skip.frontend>false</skip.frontend>
  </properties>

  <profiles>
    <profile>
      <id>dev</id>
      <properties>
        <skip.frontend>true</skip.frontend>
      </properties>
    </profile>
  </profiles>

  <build>
    <resources>
      <resource>
        <directory>${project.basedir}/dist/iis-client/browser</directory>
        <targetPath>static/app</targetPath>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>${frontend-maven-plugin.version}</version>
        <configuration>
          <workingDirectory>${project.basedir}</workingDirectory>
          <installDirectory>${project.build.directory}/node</installDirectory>
          <skip>${skip.frontend}</skip>
        </configuration>
        <executions>
          <execution>
            <id>install-node-and-npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>${node.version}</nodeVersion>
              <npmVersion>${npm.version}</npmVersion>
            </configuration>
          </execution>
          <execution>
            <id>npm-install</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>ci</arguments>
            </configuration>
          </execution>
          <execution>
            <id>npm-build</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <arguments>run build -- --configuration=production</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
